# Generated by Django 5.2.3 on 2026-01-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('GH', 'Group Head'), ('HR', 'HR')], max_length=10)),
                ('group_head', models.CharField(blank=True, max_length=10, null=True)),
                ('hr', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_activity', models.TextField()),
                ('next_week_activity', models.TextField()),
                ('leave_taken', models.IntegerField(default=0)),
                ('next_week_plan', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.employee')),
            ],
        ),
    ]
