# Generated by Django 5.2.3 on 2026-02-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group_head',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_week_activity', models.TextField()),
                ('next_week_activity', models.TextField()),
                ('leave_taken', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
