# Generated by Django 5.2.3 on 2026-02-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_employee_group_head_remove_employee_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
