# Generated by Django 5.2.3 on 2026-02-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_weeklyreport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreport',
            old_name='status',
            new_name='gh_status',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='hr_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
