# Generated by Django 5.2.3 on 2026-02-18 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_rename_status_weeklyreport_gh_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('GH', 'Group Head'), ('HR', 'HR')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
