# Generated by Django 5.2.3 on 2026-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_employee_role_weeklyreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Group Head', 'Group Head'), ('HR', 'HR')], default='EMPLOYEE', max_length=20),
        ),
    ]
